"""
Pydantic models for the AccessLens Accessibility Audit API.

Defines all request/response schemas used by the audit pipeline:
- AuditRequest: Input URL to audit
- AccessibilityIssue: Individual WCAG violation with severity and fix suggestion
- DLInsight: AI model detection with confidence score
- CategoryScore: Per-WCAG-principle score breakdown
- AuditReport: Complete audit output with score, issues, and AI insights
"""
from pydantic import BaseModel, Field
from typing import Optional, List
from enum import Enum
from datetime import datetime


class SeverityLevel(str, Enum):
    """Issue severity classification.
    
    Critical: Direct WCAG violation, major impact on accessibility (score impact >= 5)
    Warning: Potential issue or best-practice violation (score impact < 5)
    Info: Informational finding, no direct WCAG violation
    """
    CRITICAL = "critical"
    WARNING = "warning"
    INFO = "info"


class WCAGLevel(str, Enum):
    """WCAG 2.1 conformance levels (A, AA, AAA)."""
    A = "A"
    AA = "AA"
    AAA = "AAA"


class AuditRequest(BaseModel):
    """Request body for the /api/audit endpoint."""
    url: str = Field(..., description="The website URL to audit for accessibility")
    include_ai: bool = Field(True, description="Whether to run AI/CNN model analysis")


class AccessibilityIssue(BaseModel):
    """A single accessibility issue found during the audit.
    
    Each issue maps to a specific WCAG criterion and includes:
    - The HTML element causing the issue
    - A human-readable description
    - A suggested fix
    - Severity classification (critical/warning/info)
    """
    id: str = Field(..., description="Unique issue identifier (e.g., 'img-alt-missing-1')")
    wcag_criterion: str = Field(..., description="WCAG 2.1 criterion (e.g., '1.1.1')")
    wcag_level: WCAGLevel = Field(..., description="WCAG conformance level")
    severity: SeverityLevel = Field(..., description="Issue severity")
    title: str = Field(..., description="Short issue title")
    description: str = Field(..., description="Detailed description of the issue")
    element: Optional[str] = Field(None, description="HTML element causing the issue")
    selector: Optional[str] = Field(None, description="CSS selector for the element")
    data_al_id: Optional[str] = Field(None, description="Unique ID for bounding box lookup")
    suggestion: str = Field(..., description="Suggested fix for the issue")
    score_impact: float = Field(0, description="How much this issue reduces the score")


class DLInsight(BaseModel):
    """AI/Deep Learning model insight from the CNN analysis.
    
    Generated by the trained ViT-B/16 Vision Transformer model analyzing
    page screenshots for visual accessibility violations.
    """
    category: str = Field(..., description="Violation category (e.g., 'low_contrast')")
    confidence: float = Field(..., description="Model confidence score (0.0 to 1.0)")
    severity: SeverityLevel = Field(..., description="Derived severity level")
    title: str = Field(..., description="Human-readable insight title")
    description: str = Field(..., description="Detailed explanation")
    wcag_criterion: Optional[str] = Field(None, description="Related WCAG criterion")
    suggestion: Optional[str] = Field(None, description="Suggested improvement")


class CategoryScore(BaseModel):
    """Score breakdown for a WCAG principle category.
    
    WCAG has 4 principles: Perceivable, Operable, Understandable, Robust.
    Plus an additional 'AI Analysis' category for CNN model findings.
    """
    name: str = Field(..., description="Category name")
    score: float = Field(..., description="Category score (0-100)")
    max_score: float = Field(100, description="Maximum possible score")
    issue_count: int = Field(0, description="Number of issues in this category")
    description: str = Field("", description="Category description")


class AuditReport(BaseModel):
    """Complete accessibility audit report.
    
    Combines rule-based WCAG checks with AI model analysis
    to produce a comprehensive accessibility assessment.
    """
    url: str = Field(..., description="Audited URL")
    timestamp: str = Field(..., description="ISO timestamp of the audit")
    overall_score: float = Field(..., description="Overall accessibility score (0-100)")
    grade: str = Field(..., description="Letter grade (A, B, C, D, F)")
    total_issues: int = Field(0, description="Total number of issues found")
    critical_count: int = Field(0, description="Number of critical issues")
    warning_count: int = Field(0, description="Number of warning issues")
    issues: List[AccessibilityIssue] = Field(default_factory=list)
    dl_insights: List[DLInsight] = Field(default_factory=list)
    categories: List[CategoryScore] = Field(default_factory=list)
    screenshot: Optional[str] = Field(None, description="Base64 encoded screenshot")
    attention_heatmap: Optional[str] = Field(None, description="Base64 encoded Grad-CAM heatmap")
    reading_order: Optional[dict] = Field(None, description="Reading order analysis results")
    scan_duration: float = Field(0, description="Audit duration in seconds")
    ai_model_used: bool = Field(False, description="Whether AI model was used")
    limitations: List[str] = Field(
        default_factory=lambda: [
            "AI model is trained on synthetic data and may miss real-world edge cases",
            "Color contrast checks require computed styles — JavaScript-rendered colors may be missed",
            "Rule-based checks cover ~30-40% of WCAG criteria — manual testing is still required",
            "Small dataset (5,500 samples) limits model generalization to unseen layouts",
            "Dynamic content (SPAs, lazy-loaded elements) may not be fully captured",
        ]
    )
